# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - lerobot_group_controller
    - lerobot_gripper_controller

  lerobot_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
  lerobot_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - Wrist_Roll
      - Gripper
