# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    hardware_interface:
      type: gazebo_ros2_control/GazeboSystem
      
    lerobot_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    lerobot_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

lerobot_group_controller:
  ros__parameters:
    joints:
      - Shoulder_Rotation
      - Shoulder_Pitch
      - Elbow
      - Wrist_Pitch
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

lerobot_gripper_controller:
  ros__parameters:
    joints:
      - Wrist_Roll
      - Gripper
    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity
